const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  userId: String,
  userName: String,
  userPhone: String,
  userPhotoUrl: String,
  userVerified: Boolean,
  userPhoneHidden: { type: Boolean, default: false },
  items: [{
    name: String,
    price: Number,
    originalPrice: Number,
    prix: Number,
    image: String,
    imageUrl: String,
    quantity: Number,
    purchaseStatus: String,
    uiStyle: Number,
    capacite: String,
    templateName: String,
    storeName: String,
    storeId: String,
    storeLat: Number,
    storeLng: Number,
    sizes: [mongoose.Schema.Types.Mixed],
    extraImages: [String],
    variants: [mongoose.Schema.Types.Mixed],
    finalPrice: Number,
    note: String,
    alternativeName: String,
    alternativePrice: Number,
    alternativeStatus: String,
    productId: String,
    categorieId: String,
  }],
  subtotal: Number,
  deliveryFee: Number,
  total: Number,
  address: String,
  userLat: Number,
  userLng: Number,
  storeLat: Number,
  storeLng: Number,
  storeIds: [String],
  doorNumber: String,
  doorColor: String,
  locationImage: String,
  housingType: String,
  floor: String,
  userCityName: String,
  userCityNameFr: String,
  driverNote: String,
  isFreeDelivery: { type: Boolean, default: false },
  pricingDetails: mongoose.Schema.Types.Mixed,
  magasinId: String,
  driverId: String,
  driverName: String,
  driverLat: Number,
  driverLng: Number,
  status: { type: String, default: 'pending' },
  hiddenFor: [String],
  cancelReason: String,
  cancelledBy: String,
  cancelledByName: String,
  customerConfirmed: Boolean,
  counterOffer: {
    status: String,
    driverId: String,
    proposedPrice: Number,
    driverName: String,
  },
  orderId: String,
  createdAt: { type: Date, default: Date.now },
  updatedAt: Date,
  acceptedAt: Date,
  deliveredAt: Date,
});

orderSchema.index({ userId: 1, createdAt: -1 });
orderSchema.index({ driverId: 1, status: 1 });
orderSchema.index({ status: 1, createdAt: -1 });
orderSchema.index({ storeId: 1, status: 1 });

module.exports = mongoose.model('Order', orderSchema, 'orders');
